<a href="https://colab.research.google.com/github/BobbyLeeSH/ML_STUDY/blob/main/tf_iris_species.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification of Iris Species

In [1]:
# Import Libraries
import tensorflow as tf
import pandas as pd

In [2]:
# get data
data_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(data_path)
print(iris.head())

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa


In [3]:
# one-hot encoding
# to make the categorial column into columns of 1 and 0
iris = pd.get_dummies(iris)

In [4]:
# Features, Labels
Features = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
Labels = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(Features.shape, Labels.shape)

(150, 4) (150, 3)


In [6]:
# model structure
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

```
X = tf.keras.layers.Input(shape=[4])
```
means we have 4 Features
```
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
```
means we have 3 Labels and use softmax as activation
```
model.compile(loss='categorical_crossentropy', metrics='accuracy')
```
means categorical crossentropy will be used for loss calculation and accuracy will be shown together with loss.


In [7]:
# Fit model
model.fit(Features, Labels, epochs=1000, verbose=0)
model.fit(Features, Labels, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1525 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1525 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1521 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1523 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1524 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1517 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1517 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1516 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1518 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1512 - accuracy: 0.9733


In [8]:
# use model for predcition
# first 5 rows
print(model.predict(Features[:5]))
print(Labels[:5])
 
# last 5 rows
print(model.predict(Features[-5:]))
print(Labels[-5:])

[[9.9923658e-01 7.6345931e-04 4.1752468e-08]
 [9.9689388e-01 3.1057489e-03 3.6941680e-07]
 [9.9848878e-01 1.5110773e-03 1.6159881e-07]
 [9.9616784e-01 3.8314506e-03 7.2481311e-07]
 [9.9937868e-01 6.2133273e-04 3.5036429e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
[[3.9145900e-07 1.2395742e-01 8.7604225e-01]
 [1.1594639e-06 2.0966819e-01 7.9033071e-01]
 [1.9247286e-06 2.2808149e-01 7.7191657e-01]
 [2.6709768e-07 7.2689369e-02 9.2731035e-01]
 [4.0529280e-06 2.3491289e-01 7.6508307e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [10]:
# check weights and bias of the model
model.get_weights()

[array([[ 1.2918826e+00,  7.5642544e-01, -5.7233703e-01],
        [ 3.6206326e+00,  1.0238199e+00,  1.2898205e-03],
        [-3.8719134e+00, -7.7431315e-01,  9.0192389e-01],
        [-4.5241518e+00, -8.9086664e-01,  2.4493182e+00]], dtype=float32),
 array([ 1.6622401,  1.2417322, -1.2313501], dtype=float32)]

# Have done some prediction on classification with one-hot encoding and softmax activation